title: guides.martysmods.com
description: Your extensive guide site for all things ReShade.
theme: just-the-docs

url:
repository: jorban-martysmods/jorban-martysmods.github.io # for github-metadata

#Site Logo
logo: "/assets/mmlogo.webp"

include:
  - /assets/fonts/

permalink: pretty

#Search Settings
search_enabled: true
search:

# Split pages into sections that can be searched individually
heading_level: 2

# Maximum amount of previews per search result
previews: 4

# Maximum amount of words to display before a matched word in the preview
preview_words_before: 6

# Maximum amount of words to display after a matched word in the preview
preview_words_after: 6

# Set the search token separator
# Default: /[\s\-/]+/
# Example: enable support for hyphenated search words
tokenizer_separator: /[\s/]+/

# Display the relative url in search results
# Supports true (default) or false
rel_url: true

# Enable or disable the search button that appears in the bottom right corner of every page
# Supports true or false (default)
button: false

# Aux links for the upper right navigation
aux_links:
  "martysmods.com":
    - "https://martysmods.com"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
# Supports true (default) or false
heading_anchors: true

# Footer content
# appears at the bottom of every page's main content
markup / liquid-based content.:
footer_content: "Copyright &copy; 2024 MartysMods."

# Footer last edited timestamp
last_edit_timestamp: false # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

callouts_level: quiet # or loud
callouts:

  highlight:
    color: yellow

  important:
    title: Important
    color: blue

  note:
    title: Note
    color: purple

  warning:
    title: Warning
    color: red 

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Set favicon
favicon_ico: "/assets/favicon.ico"

# Add support for Jekyll Ideal Image Slider https://github.com/jekylltools/jekyll-ideal-image-slider
iis_slider_array: []